/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family: WeatherIcons
///      fonts:
///       - asset: fonts/WeatherIcons.ttf
///
///
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
///
import 'package:flutter/widgets.dart';

class WeatherIcons {
  WeatherIcons._();

  static const _kFontFam = 'WeatherIcons';

  static const IconData windy = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData cloud = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData cloudFlash = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData cloudFlashAlt = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData drizzle = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData rain = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData fog = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData cloudsFlashAlt =
      IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData sunrise = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData sun = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData moon = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData eclipse = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData mist = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData wind = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData snowflake = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData cloudSun = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData cloudMoon = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData fogSun = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData fogMoon = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData fogCloud = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData windyRain = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData snow = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData snowAlt = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData snowHeavy = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData hail = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData clouds = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData cloudsFlash = IconData(0xe820, fontFamily: _kFontFam);
}
